name: build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: Is this a release build?
        type: boolean
        required: true
        default: false

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
    runs-on: ubuntu-latest
    env:
      IS_RELEASE: ${{ github.event.inputs.release }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew runGametest

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
